GET http://localhost:3001/api/persons
###
GET http://localhost:3001/api/persons/647defbd1e0647e73eef5753
###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "JJ",
    "number": "33333333" 
}
###
DELETE http://localhost:3001/api/persons/647defbd1e0647e73eef5753



